//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cakes_and_Pastries_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cakes_and_PastriesEntities1 : DbContext
    {
        public Cakes_and_PastriesEntities1()
            : base("name=Cakes_and_PastriesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_Login> Admin_Login { get; set; }
        public virtual DbSet<Cakes_and_Pastries_Details> Cakes_and_Pastries_Details { get; set; }
        public virtual DbSet<Customer_Details> Customer_Details { get; set; }
        public virtual DbSet<Delivery_Details> Delivery_Details { get; set; }
        public virtual DbSet<Delivery_Employee_Details> Delivery_Employee_Details { get; set; }
        public virtual DbSet<Order_delivery_Details> Order_delivery_Details { get; set; }
        public virtual DbSet<Ordered_Cake_Details> Ordered_Cake_Details { get; set; }
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<Add_to_Cart> Add_to_Cart { get; set; }
    }
}
