//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cakes_and_Pastries_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Cakes_and_Pastries_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cakes_and_Pastries_Details()
        {
            this.Ordered_Cake_Details = new HashSet<Ordered_Cake_Details>();
            this.FeedBacks = new HashSet<FeedBack>();
        }


        [DisplayName("Cake Image")]
        public string Cake_Image { get; set; }
        [DisplayName("Cake ID")]
        public string Cake_ID { get; set; }
        [DisplayName("Cake and Pastries Type")]
        public string Cake_and_Pastries_Type { get; set; }
        [DisplayName("Cake Name")]
        public string Cake_Name { get; set; }
        [DisplayName("Price")]
        public Nullable<int> Price { get; set; }
        [DisplayName("Cake Type ID")]
        public Nullable<int> Cake_Type_ID { get; set; }
        [DisplayName("Cake Description")]
        public string Cake_Description { get; set; }
    
        public virtual Add_to_Cart Add_to_Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordered_Cake_Details> Ordered_Cake_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBack> FeedBacks { get; set; }
        public HttpPostedFileBase cakeimg { get; set; }
    }
}
