//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cakes_and_Pastries_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer_Details()
        {
            this.Ordered_Cake_Details = new HashSet<Ordered_Cake_Details>();
            this.Add_to_Cart = new HashSet<Add_to_Cart>();
        }

        [Required(ErrorMessage = "This feild is required")]
        [EmailAddress(ErrorMessage ="Invalid")]
        [DisplayName("Email-ID")]
        public string Email_ID { get; set; }
        [Required(ErrorMessage = "This feild is required")]
        [DisplayName("Customer Name")]

        public string Customer_Name { get; set; }
        [Required(ErrorMessage = "This feild is required")]
        [DisplayName("Password")]
        public string Password { get; set; }
        [Required(ErrorMessage ="This field is required!!")]
        [DisplayName("Mobile Number")]
        //[System.ComponentModel.DataAnnotations.CompareAttribute("Password"),ErrorMessage="Password does not match"]
        //public string Confirm_Password { get; set; }

        public string Mobile_Number { get; set; }
    
        public virtual Delivery_Details Delivery_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordered_Cake_Details> Ordered_Cake_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Add_to_Cart> Add_to_Cart { get; set; }
    }
}
