//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cakes_and_Pastries_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Delivery_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery_Details()
        {
            this.Order_delivery_Details = new HashSet<Order_delivery_Details>();
        }

        [DisplayName("Email-ID")]
        public string Email_ID { get; set; }
        [DisplayName("Customer")]
        public string Customer_Name { get; set; }
        [DisplayName("Mobile Number")]
        public string Mobile_Number { get; set; }
        [DisplayName("Delivery Address")]
        public string Delivery_Address { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [DisplayName("Date of Delivery")]
        public Nullable<System.DateTime> Date_Of_Delivery { get; set; }
        [DataType(DataType.Time)]
        [DisplayFormat(DataFormatString = "{0:}", ApplyFormatInEditMode = true)]
        [DisplayName("Time of Delivery")]
        public Nullable<System.TimeSpan> Time_Of_Delivery { get; set; }
    
        public virtual Customer_Details Customer_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_delivery_Details> Order_delivery_Details { get; set; }
    }
}
