//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cakes_and_Pastries_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Delivery_Employee_Details
    {
        [DisplayName("Delivery Employee ID")]
        public string Delivery_Employee_ID { get; set; }
        [DisplayName("Delivery Employee Name")]
        public string Delivery_Employee_Name { get; set; }
        [DisplayName("Employee Mobile Number")]
        public string Delivery_Employee_Mobile_Number { get; set; }
        [DisplayName("Delivery Employee Password")]
        public string Delivery_Employee_Password { get; set; }
    
        public virtual Order_delivery_Details Order_delivery_Details { get; set; }
    }
}
