//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cakes_and_Pastries_Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class FeedBack
    {
        [DisplayName("Feedback")]
        public int FeedBack_No { get; set; }
        [DisplayName("Cake ID")]
        public string Cake_ID { get; set; }
        [DisplayName("Cake Name")]
        public string Cake_Name { get; set; }
        [DisplayName("Rating")]
        public string Rating { get; set; }
        [DisplayName("Description")]
        public string Description { get; set; }
    
        public virtual Cakes_and_Pastries_Details Cakes_and_Pastries_Details { get; set; }
    }
}
